import = ["~/.config/alacritty/themes/cambell.yaml"]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[window]
opacity = 1
option_as_alt = "Both"
title = "Alacritty"

[window.padding]
x = 5
y = 5
