theme = "base16_transparent"

[editor]
line-number = "relative"
mouse = true
auto-format = true
rulers = [120]
bufferline = "multiple"
color-modes = true
true-color = true

[keys.normal]
g = {a = "code_action"}
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
"H" = ":buffer-next"
"L" = ":buffer-previous"
"C-/" = "toggle_comments"
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
# space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = false
character = '|'

