
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-04T09:32:59-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "c545ccb5f8ccf284a4ab0d2a19f2d4458ff5ba70",
 "version": "5.0.0a9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
